# Trigger when commits are pushed to the master branch
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:


jobs:
  terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Checkout go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16' # The Go version to download (if necessary) and use.

    - name: Go version
      id: Version
      run: go version

    - name: Go ls
      run: ls